import type { Metadata } from 'next'
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import './global.css';
import { Open_Sans } from 'next/font/google';

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'News',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={openSans.className}>
          <Header />
          <main className='wrapper'>
            {children}
          </main>
          <Footer />
        </body>
    </html>
  )
}
